routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\CategoryController;

Route::get('/', [CategoryController::class,'index'])->name('home_index');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/profile/update_photo', 'ProfileController@updatePhoto')->name('profile.update_photo');
Route::get('/profile', 'ProfileController@index')->name('profile.index');
//Route::get('/category','CategoryController@index')->name('category.index');
Route::get('/item/{id}','ItemController@show')->name('item.show');
//Route::get('/category/create','CategoryController@create')->name('category.create');
Route::resource('category', 'CategoryController') -> names('category');
Route::get('/shop/create','ShopController@create') -> name('shop.create');
Route::post('/shop/store','ShopController@store') -> name('shop.store');
Route::get('/shop_items/create','ShopItemsController@create') -> name('shopitems.create');
Route::get('/shop_items/{id}','ShopItemsController@show') -> name('shopitems.show');
Route::get('/order', 'OrderController@index')->name('order.index');
Route::get('/order/{id}', 'OrderController@show')->name('order.show');
Route::get('/order/put/{id}', 'OrderController@addOrderItem')->name('order.add');

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    protected $fillable = [
        'user_id',
        'category_id',
        'title',
        'slug',
        'description',
        'created_at',
        'updated_at'
    ];
    public function orders()
    {
         return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\CategoryRepository;
use App\Models\Shop;
use App\Http\Requests\ShopCreate;

/**
 * Class ShopController
 * @package App\Http\Controllers
 */
class ShopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Создание нового магазина
     * @param App\Repositories\CategoryRepository $repository
     * @return \Illuminate\Http\Response
     */
    public function create(CategoryRepository $repository)
    {
        $categories = $repository -> getCategories();
        return view('shop.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ShopCreate  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ShopCreate $request)
    {
        $data = $request -> validated();
        $data['user_id'] = \Auth::id();
        $data['slug'] = str_slug($data['title']);
        $shop = new Shop();
        $shop -> fill($data) -> save();
        if ($shop) {
            return redirect()
            -> route('profile.index')
            -> with(['success' => 'Магазин добавлен']);
        } else {
            return back() -> withErrors(['msg' => 'Ошибка сохранения']) -> withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/shop/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            Добавить новый магазин
                        </div>
        
                        <div class="card-body">
                                <form method="POST" action="{{ route('shop.store') }}">
                                        @csrf
                
                                        <div class="form-group row">
                                            <label for="title" class="col-md-4 col-form-label text-md-right">Название</label>
                
                                            <div class="col-md-6">
                                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>
                
                                                @error('title')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="category_id" class="col-md-4 col-form-label text-md-right">Выберите категорию</label>
                
                                            <div class="col-md-6">
                                                <select name="category_id" class="form-control @error('category_id') is-invalid @enderror" required>
                                                    @foreach($categories as $category)
                                                        <option value="{{ $category -> id }}">{{ $category -> title }}</option>
                                                    @endforeach
                                                </select>
                
                                                @error('category_id')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                                <label for="description" class="col-md-4 col-form-label text-md-right">Описание</label>
                    
                                                <div class="col-md-6">
                                                    <textarea name="description" class="form-control @error('description') is-invalid @enderror" rows="8">{{ old('description') }}</textarea>
                    
                                                    @error('description')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>

                                        <div class="form-group row mb-0">
                                                <div class="col-md-8 offset-md-4">
                                                    <button type="submit" class="btn btn-primary">
                                                        Создать
                                                    </button>
                                                </div>
                                        </div>
                                </form>
                        </div>
                    </div>
            </div>
    </div>
</div>
@endsection

resources/views/shop/items_add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            Добавить новый товар
                        </div>
        
                        <div class="card-body">
                                <form method="POST" action="{{ route('shop.store') }}">
                                        @csrf
                
                                        <div class="form-group row">
                                            <label for="title" class="col-md-4 col-form-label text-md-right">Название</label>
                
                                            <div class="col-md-6">
                                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>
                
                                                @error('title')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                                <label for="description" class="col-md-4 col-form-label text-md-right">Описание</label>
                    
                                                <div class="col-md-6">
                                                    <textarea name="description" class="form-control @error('description') is-invalid @enderror" rows="8">{{ old('description') }}</textarea>
                    
                                                    @error('description')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>

                                        <div class="form-group row mb-0">
                                                <div class="col-md-8 offset-md-4">
                                                    <button type="submit" class="btn btn-primary">
                                                        Создать
                                                    </button>
                                                </div>
                                        </div>
                                </form>
                        </div>
                    </div>
            </div>
    </div>
</div>
@endsection

resources/views/shop/items_show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
              @if (session('success'))
                <div class="alert alert-info alert-dismissible fade show text-center" role="alert">
                    {{ session('success') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
              @endif
                <div class="card-header">
                    <a href="{{ route('category.show',$shop->category_id) }}">Магазины</a> | {{ $shop -> title }}
                </div>
                <div class="card-body">
                        <table class="table">
                                <thead>
                                  <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Изо</th>
                                    <th scope="col">Название</th>
                                    <th scope="col">Остаток</th>
                                    <th scope="col">Цена</th>
                                    <th scope="col">Добавить</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    @foreach ($paginator as $item)
                                  <tr @if($item->count < 10) style="background-color:#EDDBE4" @endif>
                                    <th scope="row">{{ $item -> item_id }}</th>
                                  <td><img src="https://picsum.photos/id/{{ $item -> item_id }}/42"/></td>
                                    <td><a href="{{ route('item.show', $item -> item_id) }}">{{$item -> getItem -> title }}</a></td>
                                    <td>{{ $item -> count }}</td>
                                    <td>{{ $item -> price }}</td>
                                    <td>
                                      <a href="{{ route('order.add', $item -> id ) }}">
                                        <img src="{{ asset('images/add.png') }}" alt="Добавить в корзину"/>
                                      </a>
                                    </td>
                                  </tr>
                                  @endforeach
                                </tbody>
                        </table>
                        <div class="row justify-content-center">
                            @include('vendor.pagination.simple-bootstrap-4')
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection