routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\CategoryController;

Route::get('/', [CategoryController::class,'index'])->name('home_index');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/profile/update_photo', 'ProfileController@updatePhoto')->name('profile.update_photo');
Route::get('/profile', 'ProfileController@index')->name('profile.index');
//Route::get('/category','CategoryController@index')->name('category.index');
Route::get('/item/{id}','ItemController@show')->name('item.show');
//Route::get('/category/create','CategoryController@create')->name('category.create');
Route::resource('category', 'CategoryController') -> names('category');
Route::get('/shop/create','ShopController@create') -> name('shop.create');
Route::post('/shop/store','ShopController@store') -> name('shop.store');
Route::get('/shop_items/create','ShopItemsController@create') -> name('shopitems.create');
Route::get('/shop_items/{id}','ShopItemsController@show') -> name('shopitems.show');
Route::get('/order', 'OrderController@index')->name('order.index');
Route::get('/order/{id}', 'OrderController@show')->name('order.show');
Route::get('/order/put/{id}', 'OrderController@addOrderItem')->name('order.add');

app/Models/Category.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $fillable = [
        'title',
        'slug',
        'created_at',
        'updated_at',
        'description'
    ];
    /**
     * Получаем список магазинов по id категории
     *
     * @return \Illuminate\Database\Eloquent\Relations\Relation
     */
    public function getShops() {
        return $this -> hasMany(Shop::class);
    }

    /**
     * Получить пользователя магазина
     *
     * @return \Illuminate\Database\Eloquent\Relations\Relation
     */
    public function getUser() {
        return $this -> hasMany(User::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryCreate as CategoryCreateRequest;
use App\Models\Category;
use App\Repositories\CategoryRepository;

/**
 * Class CategoryController
 * @package App\Http\Controllers
 */
class CategoryController extends Controller
{

    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    /**
     * CategoryController constructor.
     * @param CategoryRepository $categoryRepository
     */
    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Вывод категорий магазинов
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryRepository->getCategories();
        return view('category.index', compact('categories'));
    }

    /**
     * Получаем список магазинов в заданной категории
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $category = $this->categoryRepository->getCategory($id);
        $shops = $category->getShops;
        return view('category.show', compact('shops', 'category'));
    }

    /**
     * Вывод страницы с созданием категории
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('create',Category::class);
        return view('category.create');
    }

    /**
     * Сохранение новой категории
     * @param CategoryCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryCreateRequest $request)
    {
        $data = $request->validated();
        $category = $this -> categoryRepository -> createCategory($data);
        if ($category) {
            return redirect()
                ->route('category.index')
                ->with(['success' => 'Категория добавлена']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Добавить новую категорию
                    </div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('category.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="title" class="col-md-4 col-form-label text-md-right">Название новой
                                    категории</label>

                                <div class="col-md-6">
                                    <input id="title" type="text"
                                           class="form-control @error('title') is-invalid @enderror" name="title"
                                           value="{{ old('title') }}" required autocomplete="title" autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">Описание
                                    категории</label>

                                <div class="col-md-6">
                                    <textarea name="description"
                                              class="form-control @error('description') is-invalid @enderror"
                                              rows="8">{{ old('description') }}</textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Создать
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Категории магазинов</div>

                <div class="card-body">
                    @if (!$categories -> isEmpty())
                 <div class="row justify-content-center">
                        @foreach ($categories as $category)
                            <div class="col-md-4">
                                <div class="card" style="margin-bottom:10px">
                                    <div class="card-header text-center">
                                        <a href="{{ route('category.show', $category->id) }}">{{ $category -> title }}</a>
                                    </div>
                                    <div class="card-body">
                                        {{ $category -> description }}
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    @else
                        <div class="row justify-content-center"><h4>Категории не созданы</h4></div>
                    @endif
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="row">
                <a class="btn btn-primary" href="{{ route('category.create') }}">Добавить категорию</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="{{ route('category.index') }}">Категории</a> | {{ $category -> title }}</div>

                <div class="card-body">
                    @if (!$shops -> isEmpty())
                    <div class="row justify-content-center">
                        @foreach ($shops as $shop)
                            <div class="col-md-4">
                                <div class="card" style="margin-bottom:10px">
                                    <div class="card-header text-center">
                                        <a href="{{ route('shopitems.show', $shop->id) }}">
                                            {{ $shop -> title }}
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        {{ $shop -> description }}
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    @else
                        <div class="row justify-content-center"><h4>Нет магазинов в данной категории</h4></div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection